@extends('admin.layout')
@section('content')
@php
    extract($dashboard);
    $lineMax = max(1, max(array_column($trend, 'total')));
    $linePoints = collect($trend)->values()->map(function ($day, $index) use ($lineMax, $trend) {
        $x = 18 + ($index * (264 / max(1, count($trend) - 1)));
        $y = 130 - (($day['total'] / $lineMax) * 98);
        return round($x, 1).','.round($y, 1);
    })->implode(' ');
    $deliveryTotal = max(1, $sentSubmissions + $failedSubmissions);
    $sentPercent = round(($sentSubmissions / $deliveryTotal) * 100);
@endphp
<style>
    .stat-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.stat{padding:20px}.stat-label{color:#6d7890;font-size:12px;font-weight:700}.stat-value{margin:11px 0 6px;font:800 34px/1 Manrope,sans-serif;letter-spacing:-.04em}.stat-note{color:#7d889b;font-size:12px}.stat-dot{float:right;width:9px;height:9px;border-radius:50%;background:var(--blue)}.stat:nth-child(2) .stat-dot{background:var(--green)}.stat:nth-child(3) .stat-dot{background:var(--coral)}.stat:nth-child(4) .stat-dot{background:#f6b83f}.dashboard-grid{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(290px,.8fr);gap:20px;margin-bottom:20px}.chart-head{display:flex;justify-content:space-between;align-items:start;margin-bottom:18px}.chart-title{font:800 18px Manrope,sans-serif}.chart-subtitle{margin-top:5px;color:var(--muted);font-size:12px}.trend-svg{width:100%;height:190px;overflow:visible}.trend-grid{stroke:#e7ebf2;stroke-width:1}.trend-line{fill:none;stroke:var(--blue);stroke-width:3;stroke-linecap:round;stroke-linejoin:round}.trend-area{fill:url(#area);opacity:.58}.chart-labels{display:grid;grid-template-columns:repeat(7,1fr);margin:0 17px;color:#8993a4;font-size:11px;text-align:center}.donut-row{display:flex;align-items:center;gap:24px}.donut{width:142px;height:142px;border-radius:50%;background:conic-gradient(var(--green) 0 {{ $sentPercent }}%, var(--coral) {{ $sentPercent }}% 100%);display:grid;place-items:center;flex:0 0 auto}.donut-hole{display:grid;place-items:center;width:105px;height:105px;border-radius:50%;background:#fff;text-align:center}.donut-hole strong{font:800 28px/1 Manrope,sans-serif}.donut-hole span{margin-top:4px;color:var(--muted);font-size:11px}.legend{display:grid;gap:13px;width:100%}.legend-item{display:flex;justify-content:space-between;color:#526076;font-size:13px}.legend-label{display:flex;gap:8px;align-items:center}.legend-dot{width:9px;height:9px;border-radius:50%;background:var(--green)}.legend-item:last-child .legend-dot{background:var(--coral)}.origin-list{display:grid;gap:16px}.origin-top{display:flex;justify-content:space-between;gap:12px;margin-bottom:7px;font-size:13px}.origin-top span{color:var(--muted);white-space:nowrap}.bar-track{height:7px;border-radius:99px;background:#edf1f6;overflow:hidden}.bar-fill{height:100%;border-radius:99px;background:linear-gradient(90deg,var(--blue),#7291ff)}.recent-table td{padding:13px 14px}@media(max-width:1080px){.stat-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){.stat-grid,.dashboard-grid{grid-template-columns:1fr}.donut-row{align-items:flex-start}.recent-table{overflow:auto}.recent-table table{min-width:630px}}
</style>
<div class="page-head"><div><div class="eyebrow">Command center</div><h1>Good morning, {{ auth()->user()->name }}.</h1><div class="muted">A clear view of your contact delivery pipeline.</div></div><a class="button" href="{{ route('admin.sources.index') }}">Manage sources</a></div>
<section class="stat-grid"><div class="card stat"><span class="stat-dot"></span><div class="stat-label">Total submissions</div><div class="stat-value">{{ number_format($totalSubmissions) }}</div><div class="stat-note">All time activity</div></div><div class="card stat"><span class="stat-dot"></span><div class="stat-label">Delivered</div><div class="stat-value">{{ number_format($sentSubmissions) }}</div><div class="stat-note">Sent successfully via SMTP</div></div><div class="card stat"><span class="stat-dot"></span><div class="stat-label">Needs attention</div><div class="stat-value">{{ number_format($failedSubmissions) }}</div><div class="stat-note">Delivery failures to review</div></div><div class="card stat"><span class="stat-dot"></span><div class="stat-label">Active sources</div><div class="stat-value">{{ number_format($activeSources) }}</div><div class="stat-note">Trusted website origins</div></div></section>
<section class="dashboard-grid"><div class="card card-pad"><div class="chart-head"><div><div class="chart-title">Submission volume</div><div class="chart-subtitle">Inbound messages over the last 7 days</div></div><span class="badge pending">Live data</span></div><svg class="trend-svg" viewBox="0 0 300 150" preserveAspectRatio="none" role="img" aria-label="Seven-day submission trend"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-color="#305cf6" stop-opacity=".26"/><stop offset="100%" stop-color="#305cf6" stop-opacity="0"/></linearGradient></defs><line class="trend-grid" x1="18" x2="282" y1="32" y2="32"/><line class="trend-grid" x1="18" x2="282" y1="81" y2="81"/><line class="trend-grid" x1="18" x2="282" y1="130" y2="130"/><polygon class="trend-area" points="18,130 {{ $linePoints }} 282,130"/><polyline class="trend-line" points="{{ $linePoints }}"/>@foreach($trend as $index => $day) @php($x = 18 + ($index * (264 / max(1, count($trend) - 1)))) @php($y = 130 - (($day['total'] / $lineMax) * 98)) <circle cx="{{ $x }}" cy="{{ $y }}" r="3.4" fill="#fff" stroke="#305cf6" stroke-width="2"/> @endforeach</svg><div class="chart-labels">@foreach($trend as $day)<span>{{ $day['label'] }}</span>@endforeach</div></div><div class="card card-pad"><div class="chart-head"><div><div class="chart-title">Delivery health</div><div class="chart-subtitle">SMTP delivery outcome</div></div></div><div class="donut-row"><div class="donut"><div class="donut-hole"><strong>{{ $sentPercent }}%</strong><span>delivered</span></div></div><div class="legend"><div class="legend-item"><span class="legend-label"><i class="legend-dot"></i>Delivered</span><strong>{{ $sentSubmissions }}</strong></div><div class="legend-item"><span class="legend-label"><i class="legend-dot"></i>Failed</span><strong>{{ $failedSubmissions }}</strong></div></div></div></div></section>
<section class="dashboard-grid"><div class="card card-pad"><div class="chart-head"><div><div class="chart-title">Top source origins</div><div class="chart-subtitle">Where your conversations are starting</div></div><a class="nav-link" href="{{ route('admin.sources.index') }}">View sources</a></div><div class="origin-list">@php($originMax = max(1, $topOrigins->max('total') ?? 0)) @forelse($topOrigins as $origin)<div><div class="origin-top"><strong>{{ $origin->website_origin }}</strong><span>{{ $origin->total }} messages</span></div><div class="bar-track"><div class="bar-fill" style="width:{{ round(($origin->total / $originMax) * 100) }}%"></div></div></div>@empty<div class="empty"><div class="eyebrow">Awaiting activity</div><h2>No source data yet</h2><div class="muted">Your active sources will appear here when messages arrive.</div></div>@endforelse</div></div><div class="card card-pad"><div class="chart-head"><div><div class="chart-title">Queue snapshot</div><div class="chart-subtitle">Current submission status</div></div></div><div class="legend">@foreach(['pending','in_progress','resolved'] as $status)<div class="legend-item"><span class="legend-label"><i class="legend-dot" style="background:@if($status === 'resolved') var(--green) @elseif($status === 'in_progress') #f6b83f @else var(--blue) @endif"></i>{{ ucfirst(str_replace('_',' ', $status)) }}</span><strong>{{ $statusCounts[$status] }}</strong></div>@endforeach</div></div></section>
<section class="card"><div class="card-pad" style="padding-bottom:12px"><div class="chart-title">Recent submissions</div><div class="chart-subtitle">The latest messages entering your bridge</div></div><div class="recent-table table-scroll"><table><thead><tr><th>Sender</th><th>Origin</th><th>Received</th><th>Status</th></tr></thead><tbody>@forelse($recentSubmissions as $submission)<tr><td><strong>{{ $submission->first_name }} {{ $submission->last_name }}</strong><br><a href="mailto:{{ $submission->email }}">{{ $submission->email }}</a></td><td>{{ $submission->website_origin }}</td><td class="muted">{{ $submission->created_at->diffForHumans() }}</td><td><span class="badge {{ $submission->status }}">{{ str_replace('_',' ', $submission->status) }}</span></td></tr>@empty<tr><td colspan="4"><div class="empty"><div class="muted">No submissions have arrived yet.</div></div></td></tr>@endforelse</tbody></table></div></section>
@endsection
