@extends('admin.layout')
@section('content')
<style>.template-grid{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:20px}.template-field{margin-bottom:18px}.template-field label{display:block;margin-bottom:7px;color:#526076;font-size:12px;font-weight:700}.template-field input,.template-field textarea{width:100%}.template-field textarea{min-height:96px;resize:vertical;padding:11px;border:1px solid #d7deea;border-radius:8px;font:13px "DM Sans",Arial,sans-serif}.template-note{padding:16px;border-radius:8px;background:#eef2ff;color:#40528e;font-size:13px;line-height:1.6}.image-preview{width:100%;min-height:150px;display:grid;place-items:center;border:1px dashed #b8c3d4;border-radius:8px;background:#f8fafc;color:#718096;font-size:12px;overflow:hidden}.image-preview img{display:block;width:100%;height:180px;object-fit:cover}.color-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.color-grid input{height:42px;padding:4px;cursor:pointer}@media(max-width:900px){.template-grid{grid-template-columns:1fr}}@media(max-width:520px){.color-grid{grid-template-columns:1fr}}</style>
<div class="page-head"><div><div class="eyebrow">Email experience</div><h1>Template for {{ parse_url($source->origin, PHP_URL_HOST) ?: $source->origin }}</h1><div class="muted">Customize the recipient email sent for messages from this website.</div></div><div class="actions"><a class="button secondary" href="{{ route('admin.sources.template.preview', $source) }}">Preview email</a><a class="button secondary" href="{{ route('admin.sources.index') }}">Back to sources</a></div></div>
<div class="template-grid"><form class="card card-pad" method="POST" action="{{ route('admin.sources.template.update', $source) }}" enctype="multipart/form-data">@csrf @method('PATCH')
    <div class="template-field"><label for="email_subject">Email subject</label><input id="email_subject" name="email_subject" value="{{ old('email_subject', $source->email_subject) }}" placeholder="New contact form submission"></div>
    <div class="template-field"><label for="email_eyebrow">Header label</label><input id="email_eyebrow" name="email_eyebrow" value="{{ old('email_eyebrow', $source->email_eyebrow) }}" placeholder="Contact Bridge"></div>
    <div class="template-field"><label for="email_heading">Header heading</label><input id="email_heading" name="email_heading" value="{{ old('email_heading', $source->email_heading) }}" placeholder="New message received"></div>
    <div class="template-field"><label for="email_intro">Header message</label><textarea id="email_intro" name="email_intro" placeholder="A visitor submitted a contact form from your website.">{{ old('email_intro', $source->email_intro) }}</textarea></div>
    <div class="template-field"><label for="email_footer">Footer message</label><input id="email_footer" name="email_footer" value="{{ old('email_footer', $source->email_footer) }}" placeholder="This message was securely routed by Contact Bridge."></div>
    <div class="template-field"><label>Brand colors</label><div class="color-grid"><div><label for="email_header_color">Header</label><input id="email_header_color" name="email_header_color" type="color" value="{{ old('email_header_color', $source->email_header_color ?: '#111b36') }}"></div><div><label for="email_accent_color">Accent</label><input id="email_accent_color" name="email_accent_color" type="color" value="{{ old('email_accent_color', $source->email_accent_color ?: '#276ef1') }}"></div><div><label for="email_background_color">Background</label><input id="email_background_color" name="email_background_color" type="color" value="{{ old('email_background_color', $source->email_background_color ?: '#f4f7fb') }}"></div></div></div>
    <div class="template-field"><label for="email_logo">Brand logo</label><input id="email_logo" name="email_logo" type="file" accept="image/jpeg,image/png,image/webp"><div class="muted" style="margin-top:7px;font-size:12px">JPG, PNG, or WebP. Maximum 2 MB. Displayed at up to 160 x 52 px.</div></div>
    @if($source->email_logo_path)<label class="muted" style="display:flex;gap:8px;align-items:center;font-size:13px;margin-bottom:20px"><input type="checkbox" name="remove_logo" value="1"> Remove current logo</label>@endif
    <div class="template-field"><label for="email_header_image">Header background image</label><input id="email_header_image" name="email_header_image" type="file" accept="image/jpeg,image/png,image/webp"><div class="muted" style="margin-top:7px;font-size:12px">JPG, PNG, or WebP. Maximum 4 MB.</div></div>
    @if($source->email_header_image_path)<label class="muted" style="display:flex;gap:8px;align-items:center;font-size:13px;margin-bottom:20px"><input type="checkbox" name="remove_header_image" value="1"> Remove current image</label>@endif
    <div class="muted" style="margin:0 0 12px;font-size:12px">Save changes before opening the preview screen.</div><button class="button" type="submit">Save email template</button>
</form>
<aside class="card card-pad"><h2 style="margin-top:0">Brand assets</h2><div class="image-preview">@if($source->email_logo_path)<img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($source->email_logo_path) }}" alt="Current email logo" style="object-fit:contain;background:{{ $source->email_header_color ?: '#111b36' }}">@else No logo selected @endif</div><div class="image-preview" style="margin-top:14px">@if($source->email_header_image_path)<img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($source->email_header_image_path) }}" alt="Current email header background">@else No header image selected @endif</div><div class="template-note" style="margin-top:16px"><strong>Per-platform branding</strong><br>This template is applied only to submissions from <strong>{{ $source->origin }}</strong>. The visitor email remains the message Reply-To address.</div><div class="template-note" style="margin-top:12px;background:#fff7e8;color:#8a610d"><strong>Image compatibility</strong><br>Most modern email clients support header backgrounds. A navy fallback is always included for clients that do not.</div></aside>
</div>
@endsection
